#include "Descriptors.h"

/* 64 buton + 2 hat (2x4 bit) + 8 eksen (16 bit) */
const USB_Descriptor_HIDReport_Datatype_t PROGMEM JoystickReport[] = {
  HID_USAGE_PAGE(USAGE_PAGE_GENERIC_DESKTOP),
  HID_USAGE(USAGE_JOYSTICK),
  HID_COLLECTION(COLLECTION_APPLICATION),

    HID_USAGE_PAGE(USAGE_PAGE_BUTTON),
    HID_USAGE_MINIMUM(1), HID_USAGE_MAXIMUM(64),
    HID_LOGICAL_MINIMUM(0), HID_LOGICAL_MAXIMUM(1),
    HID_REPORT_SIZE(1), HID_REPORT_COUNT(64),
    HID_INPUT(DATA|VARIABLE|ABSOLUTE),

    HID_USAGE_PAGE(USAGE_PAGE_GENERIC_DESKTOP),
    HID_USAGE(USAGE_HAT_SWITCH),
    HID_USAGE(USAGE_HAT_SWITCH),
    HID_LOGICAL_MINIMUM(0), HID_LOGICAL_MAXIMUM(7),
    HID_PHYSICAL_MINIMUM(0), HID_PHYSICAL_MAXIMUM(7),
    HID_REPORT_SIZE(4), HID_REPORT_COUNT(2),
    HID_INPUT(DATA|VARIABLE|ABSOLUTE),

    HID_USAGE(USAGE_X), HID_USAGE(USAGE_Y), HID_USAGE(USAGE_Z),
    HID_USAGE(USAGE_RX), HID_USAGE(USAGE_RY), HID_USAGE(USAGE_RZ),
    HID_USAGE(0x32), HID_USAGE(0x33),
    HID_LOGICAL_MINIMUM(-32768), HID_LOGICAL_MAXIMUM(32767),
    HID_REPORT_SIZE(16), HID_REPORT_COUNT(8),
    HID_INPUT(DATA|VARIABLE|ABSOLUTE),

  HID_END_COLLECTION
};
